// CLI helper: enqueue an ML-analysis job (faces + OCR + CLIP, cf. lib/ml.ts) for
// every asset that still needs one — the one-shot backfill of an existing
// library. The models feed on the WebP proxy/poster the pipeline already
// generated, so the NAS RAWs are never re-read. Idempotent: re-running only
// picks up assets still missing an analysis or (with CLIP on) an embedding; the
// mlPerHour setting (Pipeline page) paces the queue so an 80k library drips
// through without pinning the box.
//
// Usage:
//   npm run ml-backfill              # enqueue onto the ml queue
//   npm run ml-backfill -- --force   # re-enqueue EVERYTHING, analyzed or not
//                                    # (e.g. after a container/model upgrade)
// Then run `npm run worker` (or leave it running) to drain the queue.
//
// One-click counterpart: the "Index for search" button on the Pipeline page
// (POST /api/pipeline/ml-backfill) — same selection via lib/ml.prepareMlBackfill.
import { pool } from "../lib/db";
import { config } from "../lib/config";
import { prepareMlBackfill } from "../lib/ml";
import { enqueueMl } from "../lib/queue";

async function main() {
  const force = process.argv.slice(2).includes("--force");

  if (!config.ml.enabled) {
    console.error(
      "ML analysis is disabled — set ML_ENABLED=true (and ML_BASE_URL) first.",
    );
    process.exit(1);
  }
  if (!config.ml.clip.enabled) {
    // Not fatal (faces/OCR still run), but the semantic-search index would stay
    // empty and a later backfill would have to re-run every job.
    console.warn(
      "WARNING: ML_CLIP_ENABLED is false — no search embeddings will be " +
        "generated by this run. Enable it first if you want semantic search.",
    );
  }

  const ids = await prepareMlBackfill(force);

  console.log(
    `Enqueuing ${ids.length} ml job(s)${force ? " (force: includes already-analyzed)" : ""}…`,
  );
  let n = 0;
  for (const id of ids) {
    await enqueueMl(id);
    if (++n % 1000 === 0) console.log(`  queued ${n}/${ids.length}`);
  }
  console.log(`Done. Queued ${n}. Run \`npm run worker\` to process them.`);

  await pool.end();
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
